/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclemanagaement;

import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        xpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ypanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        SignUpButton = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        LoginAsCombo = new javax.swing.JComboBox();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        TextPass = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        forgotButton = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LoginButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(103, 29));

        xpanel.setBackground(new java.awt.Color(0, 0, 255));
        xpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        xpanel.setPreferredSize(new java.awt.Dimension(37, 14));
        xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xpanelMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");

        javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(xpanel);
        xpanel.setLayout(xpanelLayout);
        xpanelLayout.setHorizontalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(xpanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        xpanelLayout.setVerticalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(xpanelLayout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        ypanel.setBackground(new java.awt.Color(0, 0, 255));
        ypanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ypanel.setPreferredSize(new java.awt.Dimension(40, 29));
        ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ypanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ypanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ypanelMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");

        javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(ypanel);
        ypanel.setLayout(ypanelLayout);
        ypanelLayout.setHorizontalGroup(
            ypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(ypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ypanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ypanelLayout.setVerticalGroup(
            ypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ypanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(xpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ypanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(1230, 10, 103, 30);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vehicle Management System");
        jLabel11.setMaximumSize(new java.awt.Dimension(51, 20));
        jLabel11.setMinimumSize(new java.awt.Dimension(51, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(51, 20));
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(120, 70, 930, 130);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 1));
        jLabel4.setText("Vehicles at your doorsteps...");
        jLabel4.setToolTipText("");
        jLabel4.setMaximumSize(new java.awt.Dimension(221, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(221, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(221, 25));
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(130, 160, 410, 40);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("Don't have an account?");
        jLabel16.setMaximumSize(new java.awt.Dimension(144, 16));
        jLabel16.setMinimumSize(new java.awt.Dimension(144, 16));
        jLabel16.setPreferredSize(new java.awt.Dimension(144, 16));
        kGradientPanel1.add(jLabel16);
        jLabel16.setBounds(160, 520, 230, 30);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setMinimumSize(new java.awt.Dimension(150, 10));
        kGradientPanel1.add(jSeparator7);
        jSeparator7.setBounds(160, 550, 180, 10);

        SignUpButton.setBackground(new java.awt.Color(0, 0, 0));
        SignUpButton.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        SignUpButton.setMinimumSize(new java.awt.Dimension(96, 29));
        SignUpButton.setPreferredSize(new java.awt.Dimension(96, 29));
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseExited(evt);
            }
        });
        SignUpButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 255));
        jLabel17.setText("SignUp");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        SignUpButton.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        kGradientPanel1.add(SignUpButton);
        SignUpButton.setBounds(160, 560, 150, 40);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 320));
        kGradientPanel1.add(jSeparator1);
        jSeparator1.setBounds(810, 220, 50, 350);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("LOGIN AS:");
        jLabel3.setMaximumSize(new java.awt.Dimension(69, 19));
        jLabel3.setMinimumSize(new java.awt.Dimension(69, 19));
        jLabel3.setPreferredSize(new java.awt.Dimension(69, 19));
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(910, 220, 100, 19);

        LoginAsCombo.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        LoginAsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Driver", "Passenger", "" }));
        LoginAsCombo.setMinimumSize(new java.awt.Dimension(102, 26));
        LoginAsCombo.setPreferredSize(new java.awt.Dimension(102, 26));
        kGradientPanel1.add(LoginAsCombo);
        LoginAsCombo.setBounds(930, 250, 110, 26);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setMinimumSize(new java.awt.Dimension(270, 10));
        kGradientPanel1.add(jSeparator8);
        jSeparator8.setBounds(910, 280, 270, 10);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("USERNAME:");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(910, 310, 90, 20);

        TextId.setBackground(new java.awt.Color(0, 0, 255));
        TextId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        TextId.setForeground(new java.awt.Color(255, 255, 255));
        TextId.setBorder(null);
        TextId.setDisabledTextColor(new java.awt.Color(204, 204, 255));
        TextId.setMinimumSize(new java.awt.Dimension(0, 16));
        TextId.setPreferredSize(new java.awt.Dimension(0, 16));
        TextId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextIdFocusGained(evt);
            }
        });
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        kGradientPanel1.add(TextId);
        TextId.setBounds(910, 340, 270, 30);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setMinimumSize(new java.awt.Dimension(270, 10));
        kGradientPanel1.add(jSeparator4);
        jSeparator4.setBounds(910, 375, 270, 10);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("PASSWORD:");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(920, 400, 87, 19);

        TextPass.setBackground(new java.awt.Color(0, 0, 255));
        TextPass.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        TextPass.setForeground(new java.awt.Color(255, 255, 255));
        TextPass.setBorder(null);
        TextPass.setMinimumSize(new java.awt.Dimension(0, 20));
        TextPass.setPreferredSize(new java.awt.Dimension(0, 20));
        TextPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextPassFocusGained(evt);
            }
        });
        TextPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPassActionPerformed(evt);
            }
        });
        kGradientPanel1.add(TextPass);
        TextPass.setBounds(910, 425, 270, 30);

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setMinimumSize(new java.awt.Dimension(270, 10));
        kGradientPanel1.add(jSeparator6);
        jSeparator6.setBounds(910, 460, 270, 10);

        forgotButton.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        forgotButton.setForeground(new java.awt.Color(204, 204, 255));
        forgotButton.setText("Forgot Password?");
        forgotButton.setMaximumSize(new java.awt.Dimension(104, 16));
        forgotButton.setMinimumSize(new java.awt.Dimension(104, 16));
        forgotButton.setPreferredSize(new java.awt.Dimension(104, 16));
        forgotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotButtonMouseClicked(evt);
            }
        });
        kGradientPanel1.add(forgotButton);
        forgotButton.setBounds(1140, 515, 130, 20);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setMinimumSize(new java.awt.Dimension(110, 10));
        kGradientPanel1.add(jSeparator2);
        jSeparator2.setBounds(1140, 540, 120, 10);

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setMinimumSize(new java.awt.Dimension(540, 349));
        LoginButton.setPreferredSize(new java.awt.Dimension(540, 349));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });
        LoginButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("SignIn");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        LoginButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 60, 40));

        kGradientPanel1.add(LoginButton);
        LoginButton.setBounds(920, 510, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1366, 780));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xpanelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_xpanelMouseClicked

    private void xpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xpanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_xpanelMouseEntered

    private void xpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xpanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_xpanelMouseExited

    private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ypanelMouseClicked
        // TODO add your handling code here:
        setState(Login.ICONIFIED);
    }//GEN-LAST:event_ypanelMouseClicked

    private void ypanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ypanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ypanelMouseEntered

    private void ypanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ypanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ypanelMouseExited

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Registration reg=new Registration();
        reg.setVisible(true);
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void SignUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonMouseEntered

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonMouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void TextIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdFocusGained

    private void TextPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextPassFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPassFocusGained

    private void TextPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPassActionPerformed

    private void forgotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ForgotPasswordForm fp = new ForgotPasswordForm();
        fp.setVisible(true);
    }//GEN-LAST:event_forgotButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        if(TextId.getText(). equals("") || TextPass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please fill All Fields");
        }
        else
        {
            String LoginAs=String.valueOf(LoginAsCombo.getSelectedItem());
            Admin a=new Admin();
            DriverCar d=new DriverCar();
            Passenger passing=new Passenger();
            String iidd=TextId.getText();
            String pass=TextPass.getText();
            
            if(LoginAs=="Admin")
            {
                if(a.chkAdminPass(iidd, pass))
                {
                    AdminHome ah=new AdminHome(iidd);
                    this.setVisible(false);
                    ah.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid UserID or Password");
                }
            }
            
            else if(LoginAs.equals("Driver"))
            {
                DriverCar checking =new DriverCar();
                
                if(checking.chkDriverPass(iidd, pass))
                {
                    String answer=checking.getDriverType(iidd);
                    
                    if(answer.equals("Car"))
                    {
                        String dname=d.getRDriverName(iidd);
                        int carid=d.getRCarId(iidd);
                        String carName=d.getRCarName(iidd);
                        String type="Car";
                        String plateNo=d.getRCarPlate(iidd);
                        DriverHome dh=new DriverHome(iidd,dname,type,plateNo,carid,carName);
                        this.setVisible(false);
                        dh.setVisible(true);
                    }

                    else if(answer.equals("Rickshaw"))
                    {
                        DriverRickshaw dr=new DriverRickshaw();
                        String dname=dr.getRDriverName(iidd);
                        int carid=dr.getRRickshawId(iidd);
                        String carName=dr.getRRickshawName(iidd);
                        String plateNo=dr.getRRickshawPlate(iidd);
                        String type="Rickshaw";
                        DriverHome dh=new DriverHome(iidd,dname,type,plateNo,carid,carName);
                        this.setVisible(false);
                        dh.setVisible(true);
                    }
                }
                 else
                {
                    JOptionPane.showMessageDialog(null, "Invalid UserID or Password");
                }
            }
            
            else if(LoginAs=="Passenger")
            {
                if(passing.chkPassPass(iidd, pass))
                {
                   
                    this.setVisible(false);
                    String pname=passing.getRPassengerName(iidd);
                    PassengerHome ph=new PassengerHome(iidd,pname);
                    //            BookRide psi=new BookRide(iidd,pname);
                    ph.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid UserID or Password");
                }
            }
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        LoginButton.action(null,null);
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox LoginAsCombo;
    private javax.swing.JPanel LoginButton;
    private javax.swing.JPanel SignUpButton;
    private javax.swing.JTextField TextId;
    private javax.swing.JPasswordField TextPass;
    private javax.swing.JLabel forgotButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel xpanel;
    private javax.swing.JPanel ypanel;
    // End of variables declaration//GEN-END:variables
}
